### ISSUE TITLE
where is the Qt5Xmld.pdb

### ISSUE THREAD

**Issue by RainyBow** [T12z/TCNopen-old#2]
I saw "Copy Qt5Xmld.dll and Qt5Xmld.pdb into our wireshark director" in file trdp/spy/win64/readme.txt
but I can not find the file in the directory

**Comment by RainyBow** [comment]
I find it at https://github.com/DigitalGlobe/tools/blob/master/Qt/5.7/x86/bin/Qt5Xmld.pdb, but it doest not work.
![image](https://user-images.githubusercontent.com/20679042/53946993-d66fcc80-40ff-11e9-981d-48d755983ab0.png)

**Comment by RainyBow** [comment]
system: win10 64bit 1803
wireshark:Version 2.4.11 (v2.4.11-0-ga6cc2066cf)   64bit

**Comment by T12z** [comment]
I saw something being updated about this upstream.
However, as a I badly stuffed up my pull-from-upstream-workflow on this repo, I finally decided to reboot this repository. **Sorry for the hassles**

Please see the new https://github.com/T12z/TCNopen which should have those news from upstream included.

Now, I also did some work on the trdp-spy dissector to get it to work on "modern" Wireshark versions and not crash on Linux.

see the branch at  https://github.com/T12z/TCNopen/tree/xml-spy-arry-refactor

Though this is not yet built on Windows.
